version: "2"

services:
    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - wordpress_volume:/var/www/html/wordpress
        networks:
            - inception_net

    mariadb:
        build: ./requirements/mariadb/
        container_name: mariadb
        image: mariadb
        restart: always
        expose:
            - "3306"
        volumes:
            - db_volume:/db
        networks:
            - inception_net
        depends_on:
            - nginx
        environment:
            MD_DBNAME:    ${MD_DBNAME}
            MD_ID:        ${MD_ID}
            MD_PW:        ${MD_PW}

    wordpress:
        build: ./requirements/wordpress/
        container_name: wordpress
        image: wordpress
        restart: always
        expose:
            - "9000"
        volumes:
            - wordpress_volume:/var/www/html/wordpress
        networks:
            - inception_net
        depends_on:
            - nginx
            - mariadb
        environment:
            MD_DBNAME:    ${MD_DBNAME}
            MD_ID:        ${MD_ID}
            MD_PW:        ${MD_PW}
            MD_HOST:      ${MD_HOST}
            WP_ADMIN_ID:  ${WP_ADMIN_ID}
            WP_ADMIN_PW:  ${WP_ADMIN_PW}

networks:
    inception_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "192.168.1.0/24"
                  gateway: "192.168.1.1"

volumes:
    db_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/hyojang/data/db'

    wordpress_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/hyojang/data/wordpress'
