version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        build: ./requirements/nginx/
        restart: always
        ports:
            - "80:80"
        expose:
            - "9000"
        network:
            - inception_net

    mariadb:
        container_name: mariadb
        image: mariadb
        build: ./requirements/mariadb/
        restart: always
        expose:
            - "3306"
        network:
            - inception_net

network:
    inception_net:
        driver: bridge
