version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        build: ./requirements/nginx/
        restart: always
        ports:
            - "80:80"
        expose:
            - "9000"
        #tty: true
