version: "3"

services:
    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - wordpress_volume:/var/www/html/wordpress
        networks:
            - inception_net

    mariadb:
        build: ./requirements/mariadb/
        container_name: mariadb
        image: mariadb
        restart: always
        expose:
            - "3306"
        volumes:
            - db_volume:/db
        networks:
            - inception_net
        depends_on:
            - nginx
        tty: true

    wordpress:
        build: ./requirements/wordpress/
        container_name: wordpress
        image: wordpress
        restart: always
        expose:
            - "9000"
        volumes:
            - wordpress_volume:/var/www/html/wordpress
        networks:
            - inception_net
        depends_on:
            - nginx
            - mariadb

        tty: true

networks:
    inception_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "192.168.1.0/24"
                  gateway: "192.168.1.1"

volumes:
    db_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/hyojang/data/db'

    wordpress_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/hyojang/data/wordpress'
