version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        build: ./requirements/nginx/
        restart: always
        ports:
            - "80:80"
        networks:
            - inception_net

    mariadb:
        container_name: mariadb
        image: mariadb
        build: ./requirements/mariadb/
        restart: always
        expose:
            - "3306"
        networks:
            - inception_net
        depends_on:
            - nginx

        tty: true
        volumes:
            - ./data:/data

networks:
    inception_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "192.168.1.0/24"
                  gateway: "192.168.1.1"

